### ISSUE TITLE
Why do you put mixins.js and variables.js into the src folder?  

### ISSUE THREAD

**Issue by steveCluster** [DavidWells/postCSS-tutorial#1]
Shouldn't they go into the config folder?

**Comment by DavidWells** [comment]
Yeah they can live anywhere. I just threw them in there for this demo

I keep them top level (in src) for our site: https://github.com/serverless/site/blob/master/src/_mixins.js + https://github.com/serverless/site/blob/master/src/_variables.js

**Comment by steveCluster** [comment]
Okay great thanks for the tip and for creating this tutorial.
